package view;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * data_small_frame.java
 *
 * Created on 2014-6-6, 19:23:27
 */


/**
 *
 * @author Administrator
 */
public class Data_small extends javax.swing.JPanel {

    /** Creates new form 统计 */
    public Data_small() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalNumLabel = new javax.swing.JLabel();
        totalNum = new javax.swing.JTextField();
        alreadyNumLabel = new javax.swing.JLabel();
        alreadyNum = new javax.swing.JTextField();
        correctNumLabel = new javax.swing.JLabel();
        correctNum = new javax.swing.JTextField();
        wrongNumLabel = new javax.swing.JLabel();
        wrongNum = new javax.swing.JTextField();
        correctRateLabel = new javax.swing.JLabel();
        wrongNum1 = new javax.swing.JTextField();
        wordlistNameLabel = new javax.swing.JLabel();
        wordlistName = new javax.swing.JTextField();
        Logo = new javax.swing.JPanel();
        piePanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pieGraph1 = new javax.swing.JPanel();
        piePanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pieGraph2 = new javax.swing.JPanel();

        setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(468, 357));

        totalNumLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
        totalNumLabel.setText("单词总数");

        totalNum.setText("totalNumber");

        alreadyNumLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
        alreadyNumLabel.setText("已背单词数");

        alreadyNum.setText("alreadyNumber");

        correctNumLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
        correctNumLabel.setText("正确单词数");

        correctNum.setText("correctNumber");

        wrongNumLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
        wrongNumLabel.setText("错误单词数");

        wrongNum.setText("correctNum");

        correctRateLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
        correctRateLabel.setText("正确率");

        wrongNum1.setText("correctRate");
        wrongNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongNum1ActionPerformed(evt);
            }
        });

        wordlistNameLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
        wordlistNameLabel.setText("词库名称");

        wordlistName.setText("wordlistName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(correctRateLabel)
                        .addGap(10, 10, 10)
                        .addComponent(wrongNum1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wrongNumLabel)
                        .addGap(10, 10, 10)
                        .addComponent(wrongNum, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(correctNumLabel)
                        .addGap(10, 10, 10)
                        .addComponent(correctNum, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(alreadyNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alreadyNum, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(totalNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalNum, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(wordlistNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wordlistName, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordlistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordlistNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalNumLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alreadyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alreadyNumLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correctNumLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongNumLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correctRateLabel))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 12));
        jLabel1.setText("正确率比例");

        javax.swing.GroupLayout pieGraph1Layout = new javax.swing.GroupLayout(pieGraph1);
        pieGraph1.setLayout(pieGraph1Layout);
        pieGraph1Layout.setHorizontalGroup(
            pieGraph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        pieGraph1Layout.setVerticalGroup(
            pieGraph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout piePanel1Layout = new javax.swing.GroupLayout(piePanel1);
        piePanel1.setLayout(piePanel1Layout);
        piePanel1Layout.setHorizontalGroup(
            piePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piePanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(piePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piePanel1Layout.createSequentialGroup()
                        .addComponent(pieGraph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92))))
        );
        piePanel1Layout.setVerticalGroup(
            piePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieGraph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 12));
        jLabel2.setText("总词库比例");

        javax.swing.GroupLayout pieGraph2Layout = new javax.swing.GroupLayout(pieGraph2);
        pieGraph2.setLayout(pieGraph2Layout);
        pieGraph2Layout.setHorizontalGroup(
            pieGraph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        pieGraph2Layout.setVerticalGroup(
            pieGraph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout piePanel2Layout = new javax.swing.GroupLayout(piePanel2);
        piePanel2.setLayout(piePanel2Layout);
        piePanel2Layout.setHorizontalGroup(
            piePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piePanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(piePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piePanel2Layout.createSequentialGroup()
                        .addComponent(pieGraph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95))))
        );
        piePanel2Layout.setVerticalGroup(
            piePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieGraph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(piePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(piePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(piePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(piePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void wrongNum1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
}                                         


    // Variables declaration - do not modify
    private javax.swing.JPanel Logo;
    private javax.swing.JTextField alreadyNum;
    private javax.swing.JLabel alreadyNumLabel;
    private javax.swing.JTextField correctNum;
    private javax.swing.JLabel correctNumLabel;
    private javax.swing.JLabel correctRateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pieGraph1;
    private javax.swing.JPanel pieGraph2;
    private javax.swing.JPanel piePanel1;
    private javax.swing.JPanel piePanel2;
    private javax.swing.JTextField totalNum;
    private javax.swing.JLabel totalNumLabel;
    private javax.swing.JTextField wordlistName;
    private javax.swing.JLabel wordlistNameLabel;
    private javax.swing.JTextField wrongNum;
    private javax.swing.JTextField wrongNum1;
    private javax.swing.JLabel wrongNumLabel;
    // End of variables declaration

}

